### ISSUE TITLE
Bug - account #9 TOTP does not work - asks for secret code #6 (not a typo)

### ISSUE THREAD

**Issue by cpuks** [uaraven/otpauth-ciq#10]
I found a bug when using #9 account it only gives me the option to fill Secret code #6 while it should be #9 to match the account number.
It's not a typo as TOTP in that account does not work - numbers 1-8 and 10 work just fine.
Attached screenshot
![image](https://github.com/uaraven/otpauth-ciq/assets/21194723/ac41d8d6-4281-4488-aef9-77ebc160f0df)

**Comment by uaraven** [comment]
this should be fixed by #12  

the fix will be included in v0.4.1
