### ISSUE TITLE
Use Toybox.Cryptography for calculating hashes

### ISSUE THREAD

**Issue by FD-** [uaraven/otpauth-ciq#5]
Hi,
Is there any reason why you are not using Toybox.Cryptography.Hash for calculating the SHA1? IMHO this would probably more efficient than your custom SHA1 implementation, and could enable support for TOTPs that need SHA256.

**Comment by uaraven** [comment]
I added Toybox SHA1 implementation in 779cd37a7283023a1df21a05e3b7f414beeb12df, but it's not been released yet.

**Comment by uaraven** [comment]
Done with https://github.com/uaraven/otpauth-ciq/pull/7

**Comment by FD-** [comment]
Thanks so much! Together with the SHA256 support you just added this app is now exactly what I needed!
